### ISSUE TITLE
Can we make this P2P?

### ISSUE THREAD

**Issue by Nataset** [raksitnongbua/planning-poker-service#3]
@raksitnongbua 
I wonder if it's possible to use Peer-to-Peer instead so that we can get rid of dedicated backend service.

**Comment by raksitnongbua** [comment]
@Nataset It's interesting, and it might be better in terms of performance, especially if there are a lot of users. But I'm also interested in learning how to create WebSockets in Golang, and I have never tried P2P before. 
Do you wanna try and share how to use p2p to me?
